#include "iBase_FCDefs.h"
#ifdef FC_FUNC_

#define iRel_dtor FC_FUNC_( irel_dtor, IREL_DTOR )
#define iRel_createAssociation FC_FUNC_( irel_createassociation, IREL_CREATEASSOCIATION )
#define iRel_destroyAssociation FC_FUNC_( irel_destroyassociation, IREL_DESTROYASSOCIATION )
#define iRel_getAssociatedInterfaces FC_FUNC_( irel_getassociatedinterfaces, IREL_GETASSOCIATEDINTERFACES )
#define iRel_setEntEntAssociation FC_FUNC_( irel_setententassociation, IREL_SETENTENTASSOCIATION )
#define iRel_setEntSetAssociation FC_FUNC_( irel_setentsetassociation, IREL_SETENTSETASSOCIATION )
#define iRel_setSetEntAssociation FC_FUNC_( irel_setsetentassociation, IREL_SETSETENTASSOCIATION )
#define iRel_setSetSetAssociation FC_FUNC_( irel_setsetsetassociation, IREL_SETSETSETASSOCIATION )
#define iRel_setEntEntArrAssociation FC_FUNC_( irel_setententarrassociation, IREL_SETENTENTARRASSOCIATION )
#define iRel_setSetEntArrAssociation FC_FUNC_( irel_setsetentarrassociation, IREL_SETSETENTARRASSOCIATION )
#define iRel_setEntSetArrAssociation FC_FUNC_( irel_setentsetarrassociation, IREL_SETENTSETARRASSOCIATION )
#define iRel_setSetSetArrAssociation FC_FUNC_( irel_setsetsetarrassociation, IREL_SETSETSETARRASSOCIATION )
#define iRel_setEntArrEntArrAssociation FC_FUNC_( irel_setentarrentarrassociation, IREL_SETENTARRENTARRASSOCIATION )
#define iRel_setSetArrEntArrAssociation FC_FUNC_( irel_setsetarrentarrassociation, IREL_SETSETARRENTARRASSOCIATION )
#define iRel_setEntArrSetArrAssociation FC_FUNC_( irel_setentarrsetarrassociation, IREL_SETENTARRSETARRASSOCIATION )
#define iRel_setSetArrSetArrAssociation FC_FUNC_( irel_setsetarrsetarrassociation, IREL_SETSETARRSETARRASSOCIATION )
#define iRel_getEntEntAssociation FC_FUNC_( irel_getententassociation, IREL_GETENTENTASSOCIATION )
#define iRel_getEntSetAssociation FC_FUNC_( irel_getentsetassociation, IREL_GETENTSETASSOCIATION )
#define iRel_getSetEntAssociation FC_FUNC_( irel_getsetentassociation, IREL_GETSETENTASSOCIATION )
#define iRel_getSetSetAssociation FC_FUNC_( irel_getsetsetassociation, IREL_GETSETSETASSOCIATION )
#define iRel_getEntEntArrAssociation FC_FUNC_( irel_getententarrassociation, IREL_GETENTENTARRASSOCIATION )
#define iRel_getSetEntArrAssociation FC_FUNC_( irel_getsetentarrassociation, IREL_GETSETENTARRASSOCIATION )
#define iRel_getEntArrEntArrAssociation FC_FUNC_( irel_getentarrentarrassociation, IREL_GETENTARRENTARRASSOCIATION )
#define iRel_getEntArrSetArrAssociation FC_FUNC_( irel_getentarrsetarrassociation, IREL_GETENTARRSETARRASSOCIATION )
#define iRel_getSetArrEntArrAssociation FC_FUNC_( irel_getsetarrentarrassociation, IREL_GETSETARRENTARRASSOCIATION )
#define iRel_getSetArrSetArrAssociation FC_FUNC_( irel_getsetarrsetarrassociation, IREL_GETSETARRSETARRASSOCIATION )
#define iRel_createVtxAndAssociate FC_FUNC_( irel_createvtxandassociate, IREL_CREATEVTXANDASSOCIATE )
#define iRel_createEntAndAssociate FC_FUNC_( irel_createentandassociate, IREL_CREATEENTANDASSOCIATE )
#define iRel_createVtxArrAndAssociate FC_FUNC_( irel_createvtxarrandassociate, IREL_CREATEVTXARRANDASSOCIATE )
#define iRel_createEntArrAndAssociate FC_FUNC_( irel_createentarrandassociate, IREL_CREATEENTARRANDASSOCIATE )
#define iRel_inferAllAssociations FC_FUNC_( irel_inferallassociations, IREL_INFERALLASSOCIATIONS )
#define iRel_inferEntAssociations FC_FUNC_( irel_inferentassociations, IREL_INFERENTASSOCIATIONS )
#define iRel_inferSetAssociations FC_FUNC_( irel_infersetassociations, IREL_INFERSETASSOCIATIONS )
#define iRel_inferEntArrAssociations FC_FUNC_( irel_inferentarrassociations, IREL_INFERENTARRASSOCIATIONS )
#define iRel_inferSetArrAssociations FC_FUNC_( irel_infersetarrassociations, IREL_INFERSETARRASSOCIATIONS )
#define iRel_moveTo FC_FUNC_( irel_moveto, IREL_MOVETO )
#define iRel_newAssoc FC_FUNC_( irel_newassoc, IREL_NEWASSOC )

#endif
