#!/bin/sh
#
#rm -rf moab_perf.out
#for size in 10 20 30 40 50 75 100 150 200
#do
#  ./perf $size A >> moab_perf.out
#  ./perf $size B >> moab_perf.out
#  ./perf $size C >> moab_perf.out
#done

#rm -rf cubit_perf.out
#for size in 10 20 30 40 50 75 100 150 200
#do
#  ./cubit_perf $size >> cubit_perf.out
#done

#rm -rf tstt_perf.out
#for size in 10 20 30 40 50 75 100 150 200
#do
#  ./tstt_perf $size B >> tstt_perf.out
#  ./tstt_perf $size C >> tstt_perf.out
#done

rm -rf tstt_perf_binding.out
for size in 10 20 30 40 50 75 100 150 200
do
  ./tstt_perf_binding $size B >> tstt_perf_binding.out
  ./tstt_perf_binding $size C >> tstt_perf_binding.out
done

