#
# Copyright 2006 Sandia Corporation.  Under the terms of Contract
# DE-AC04-94AL85000 with Sandia Coroporation, the U.S. Government
# retains certain rights in this software.
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
#

ITAPS_DIR = ${HOME}/MOAB/tools/iMesh/SIDL
iMesh_DIR = $(ITAPS_DIR)
iGeom_DIR = $(ITAPS_DIR)
iRel_DIR = $(ITAPS_DIR)
iBase_DIR = $(ITAPS_DIR)

# Babel definitions
SIDLDIR = /usr/local
BABEL = $(SIDLDIR)/bin/babel

MESQUITE_DIR = ${HOME}/tstt/mesquite

