Document: moab
Title: Debian moab Manual
Author: <insert document author here>
Abstract: This manual describes what moab is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/moab/moab.sgml.gz

Format: postscript
Files: /usr/share/doc/moab/moab.ps.gz

Format: text
Files: /usr/share/doc/moab/moab.text.gz

Format: HTML
Index: /usr/share/doc/moab/html/index.html
Files: /usr/share/doc/moab/html/*.html
