      parameter (iBase_VERTEX = 0) 
      parameter (iBase_EDGE = 1) 
      parameter (iBase_FACE = 2) 
      parameter (iBase_REGION = 3)
      parameter (iBase_ALL_TYPES = 4)

      parameter (iBase_NEW = 0)               
      parameter (iBase_ALREADY_EXISTED = 1)   
      parameter (iBase_CREATED_DUPLICATE = 2)
      parameter (iBase_CREATION_FAILED = 3)

      parameter (iBase_SILENT = 0) 
      parameter (iBase_WARN_ONLY = 1) 
      parameter (iBase_ABORT_ON_ERROR = 2) 
      parameter (iBase_PRINT_AND_THROW_ERROR = 3) 
      parameter (iBase_THROW_ERROR = 4)

      parameter (iBase_SUCCESS = 0)	
      parameter (iBase_MESH_ALREADY_LOADED = 1)	
      parameter (iBase_NO_MESH_DATA = 2)	
      parameter (iBase_FILE_NOT_FOUND = 3)	
      parameter (iBase_FILE_WRITE_ERROR = 4)	
      parameter (iBase_NIL_ARRAY = 5)	
      parameter (iBase_BAD_ARRAY_SIZE = 6)	
      parameter (iBase_BAD_ARRAY_DIMENSION = 7)	
      parameter (iBase_INVALID_ENTITY_HANDLE = 8)	
      parameter (iBase_INVALID_ENTITY_COUNT = 9)	
      parameter (iBase_INVALID_ENTITY_TYPE = 10)	
      parameter (iBase_INVALID_ENTITY_TOPOLOGY = 11)
      parameter (iBase_BAD_TYPE_AND_TOPO = 12)	
      parameter (iBase_ENTITY_CREATION_ERROR = 13)
      parameter (iBase_INVALID_TAG_HANDLE = 14)
      parameter (iBase_TAG_NOT_FOUND = 15)	
      parameter (iBase_TAG_ALREADY_EXISTS = 16)
      parameter (iBase_TAG_IN_USE = 17)
      parameter (iBase_INVALID_ENTITYSET_HANDLE = 18)	
      parameter (iBase_INVALID_ITERATOR_HANDLE = 19)	
      parameter (iBase_INVALID_ARGUMENT = 20)	
      parameter (iBase_MEMORY_ALLOCATION_FAILED = 21)
      parameter (iBase_NOT_SUPPORTED = 22)	
      parameter (iBase_FAILURE = 23)

      parameter (iBase_BLOCKED = 0)
      parameter (iBase_INTERLEAVED = 1)
      parameter (iBase_UNDETERMINED = 2)

      parameter (iBase_INTEGER = 0)
      parameter (iBase_DOUBLE = 1)
      parameter (iBase_ENTITY_HANDLE = 2)
      parameter (iBase_BYTES = 3)
