.TH CGM2MOAB 1 "September 2006" local
.SH NAME
cgm2moab \- Extract facetted representation of CGM geometry and write to MOAB mesh file.
.SH SYNOPSIS
.B cgm2moab [-h]

.B cgm2moab
.B [-d
.I tolerance
.B |-D] [-n
.I tolerance
.B |-N] [-l 
.I tolerance
.B |-L] [-A|-a] [-t
.I filetype
.B ]
.I input_file output_file
.SH DESCRIPTION
.B cgm2moab
reads a geometry file format supported by CGM, extracts a facetted
representation of the geometry and writes the resulting tessellation
to a MOAB-supported file format.  Geometric topology and CGM group
relations are preserved using MOAB mesh sets to the extent that the
requested output file format supports this information.
.SH OPTIONS
.IP -h
Print help to stdout and exit.
.IP "-d tol"
Maximum diviation between a facet and the cooresponding geometry.
.IP "-D"
No maixmum diviation between a facet and the corresponding geometry.
.IP "-n tol"
Maximum angle of deviation between facet normal and corresponding geometric normal.
.IP -N
No limit on angle between normals.
.IP "-l tol"
Maximum facet edge length.
.IP -L
No limit on facet edge length.
.IP -a
Actuate all CGM attributes.
.IP -A
Disable all CGM attributes.
.IP "-t type"
Specify input file type.  Default is to auto-detect.
.SH FILES
.SH ENVIRONMENT
.SH DIAGNOSTICS
